# Generated by Django 5.1 on 2024-09-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_post_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('puublished', 'Опубликовано'), ('draft', 'Черновик')], default='draft', max_length=12, verbose_name='Статус'),
        ),
    ]
